package domein;

import java.util.List;

public class Klant extends Gebruiker {
	//JPA autogenerated id
	private int klantnummer;
	private Bedrijf bedrijfsgegevens;
	private List<Contract> contracten;
	private List<Ticket> tickets;

	public Klant(String gebruikersnaam, String wachtwoord, String voornaam, String naam, String emailadres, 
			int klantnummer, Bedrijf bedrijfsgegevens) {
		super(gebruikersnaam, wachtwoord, voornaam, naam, emailadres);
		setKlantnummer(klantnummer);
		setBedrijfsgegevens(bedrijfsgegevens);
	}
	
	public int getKlantnummer() {
		return klantnummer;
	}

	private void setKlantnummer(int klantnummer) {
		this.klantnummer = klantnummer;
	}

	public Bedrijf getBedrijfsgegevens() {
		return bedrijfsgegevens;
	}

	private void setBedrijfsgegevens(Bedrijf bedrijfsgegevens) {
		this.bedrijfsgegevens = bedrijfsgegevens;
	}
}
