package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.ListView;

import javafx.scene.control.PasswordField;

import javafx.scene.input.KeyEvent;
import javafx.scene.layout.HBox;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class BedrijfBeheerSchermController extends HBox{
	@FXML private Label lblFilters;
	@FXML private TextField txfFilterBedrijfsnaam;
	@FXML private TextField txfFilterLand;
	@FXML private TextField txfFilterGemeente;
	@FXML private Button btnFiltersLeegmaken;
	@FXML private TableView tblBedrijven;
	@FXML private TableColumn tbcBedrijfsNr;
	@FXML private TableColumn tbcBedrijfsnaam;
	@FXML private TableColumn tbcLand;
	@FXML private TableColumn tbcGemeente;
	@FXML private Label lblBedrijfsgegevens;
	@FXML private Label lblBedrijfsNr;
	@FXML private Label lblBedrijfsnaam;
	@FXML private Label lblLand;
	@FXML private Label lblGemeente;
	@FXML private Label lblPostcode;
	@FXML private Label lblStraat;
	@FXML private Label lblTelefoonnummers;
	@FXML private ListView lstTelefoonnummers;
	@FXML private TextField txfKlantnr;
	@FXML private TextField txfGebruikersnaam;
	@FXML private PasswordField pwfWachtwoord;
	@FXML private TextField txfVoornaam;
	@FXML private TextField txfPostcode;
	@FXML private TextField txfStraat;
	@FXML private Label lblHuisnr;
	@FXML private TextField txfHuisnr;
	@FXML private Label lblBusnr;
	@FXML private TextField txfBusnr;
	@FXML private Button btnBedrijfsgegevensLegen;
	@FXML private Button btnBedrijfWijzigen;
	@FXML private Button btnBedrijfToevoegen;
	@FXML private Label lblKlanten;
	@FXML private TableView tblKlanten;

public BedrijfBeheerSchermController(){
		
		FXMLLoader loader = new FXMLLoader(getClass().getResource("BedrijfBeheerScherm.fxml"));
		loader.setRoot(this);
	    loader.setController(this);
	    
	    try {
	        loader.load();
	    } catch (IOException ex) {
	        throw new RuntimeException(ex);
	    }
	    
	    
	}
	// Event Listener on TextField[#txfFilterBedrijfsnaam].onKeyReleased
	@FXML
	public void filterGebruiker(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#txfFilterLand].onKeyReleased
	@FXML
	public void filterVoornaam(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#txfFilterGemeente].onKeyReleased
	@FXML
	public void filterNaam(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnFiltersLeegmaken].onAction
	@FXML
	public void clear(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBedrijfsgegevensLegen].onAction
	@FXML
	public void clearKlantgegevens(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBedrijfWijzigen].onAction
	@FXML
	public void KlantWijzigen(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnBedrijfToevoegen].onAction
	@FXML
	public void voegKlantToe(ActionEvent event) {
		// TODO Autogenerated
	}
}
